pages:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
  - docker run -t --rm -e EXAMIBUR_ACCESS_TOKEN -v $(pwd)/:/src/ python:3.6 python /src/tools/backup.py gitlab
  - docker run -t --rm -e EXAMIBUR_ACCESS_TOKEN -v $(pwd)/:/src/ python:3.6 python /src/tools/report.py "/src/backups/gitlab/" "/src/docs/projektplan/resources/export/" all
  - docker build -t engineering-projekt/examibur-website docs/website/docker/
  - docker run -t --rm --name examibur-website -u jekyll -v $(pwd)/docs/:/src/ -p 4000:4000 engineering-projekt/examibur-website jekyll build -d public
  - cp -r docs/public public/
  artifacts:
    paths:
    - public
  only:
  - master
