stages:
  - build
  - test
  - docs
  - deploy

variables:
  REGISTRY_BASE: registry.gitlab.com/engineering-projekt/examibur
  JEKYLL_IMAGE: $REGISTRY_BASE:jekyll

cache:
  paths:
    - examibur/build/
    - examibur/.gradle/

build_images:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_BASE
    - docker build -t $JEKYLL_IMAGE -f docker/Dockerfile.jekyll .
    - docker push $JEKYLL_IMAGE

build:
  image: java:8-jdk
  stage: build
  script:
    - cd examibur/
    - ./gradlew assemble
  artifacts:
    paths:
      - examibur/build/libs/

test:
  image: java:8-jdk
  stage: test
  script:
    - cd examibur/
    # - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
    - ./gradlew check
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - examibur/build/reports/

generate_pages:
  stage: docs
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_BASE
    - docker run --rm -u jekyll -v $(pwd)/docs/:/src/ $JEKYLL_IMAGE jekyll build -d public
  artifacts:
    paths:
    - docs/public/

pages:
  stage: deploy
  image: python:3.6
  script:
  - python ./tools/backup.py gitlab
  - python ./tools/report.py "./backups/gitlab/" "./docs/public/projektmanagement/resources/export/" all
  - cp -r docs/public public/
  artifacts:
    paths:
    - public
  only:
    - master
