version: '2'
services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "m4U6ctWpEZE801T"
      POSTGRES_USER: "examibur"
    networks:
      - examibur
  tomcat:
    build:
      dockerfile: ./Dockerfile.tomcat-dev
      context: ./docker/
    restart: always
    links:
      - postgres
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - ./examibur/webapps/:/usr/local/tomcat/webapps/:z
      - ./examibur/jacoco/:/var/jacoco/:z
    environment:
      DB_HOST: "postgres"
      DB_USER: "examibur"
      DB_PASSWORD: "m4U6ctWpEZE801T"
      LOG_LEVEL: "debug"
      LOG_FILE: "/usr/local/tomcat/logs/examibur.log"
    networks:
      - examibur
  website:
    user: jekyll
    build:
      dockerfile: ./Dockerfile.jekyll
      context: ./docker/ 
    ports:
    - 4000:4000
    volumes:
      - ./docs/:/src/:Z
    command: jekyll serve -d public

networks:
  examibur:
