FROM tomcat:9.0-alpine
MAINTAINER Raphael Zimmermann <raphael.zimmermann@hsr.ch>

RUN echo $CATALINA_HOME/setenv.sh
ADD jacocoagent.jar $CATALINA_HOME/lib/jacocoagent.jar
ADD setenv.sh $CATALINA_HOME/bin/setenv.sh
EXPOSE 8000
