version: '3'
services:
  nginx:
    build: ./images/nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - sonarqube
    links:
      - sonarqube
  staging:
    image: registry.gitlab.com/engineering-projekt/examibur:examibur-master
    restart: always
    links:
      - db_examibur
    depends_on:
      - db_examibur
    env_file: examibur.env

  db_examibur:
    image: postgres
    env_file: db_examibur.env
    volumes:
     - db_examibur:/var/lib/postgresql/data

  db_sonarqube:
    image: postgres
    env_file: db_sonarqube.env
    volumes:
     - db_sonarqube:/var/lib/postgresql/data

  sonarqube:
    build: ./images/sonar/
    env_file: sonarqube.env
    links:
      - db_sonarqube
    depends_on:
      - db_sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  nginx_certs:
  nginx_conf:
  db_sonarqube:
  db_examibur:
  sonarqube_data:
  sonarqube_extensions:
  gitlab_runner:
